### PR TITLE
Port fixtures from golang tar

### PR DESCRIPTION
**Pull request by danmoseley**
From https://github.com/golang/go/tree/master/src/archive/tar/testdata

Relates to https://github.com/dotnet/runtime/issues/74316

### CODE REVIEW

**Comment by danmoseley** [comment]
@carlossanlop @am11 

BTW, I also [posted a note ](https://github.com/libarchive/libarchive/issues/1767) asking for clarification about the license of the libarchive test files to be totally sure it's OK to copy them. If it's OK then I'll add those also.

**Review by carlossanlop — APPROVED** [review]
LGTM. Thank you for adding, @danmoseley !

**Comment by am11** [comment]
Thanks. I think we can add libarchive assets as well; with their license in the TPN file. If we get a reply suggesting some other approach, we can then reiterate.

**Comment by danmoseley** [comment]
> Thanks. I think we can add libarchive assets as well; with their license in the TPN file. If we get a reply suggesting some other approach, we can then reiterate.

I will wait on clarity from https://github.com/libarchive/libarchive/issues/1767

**Pull request merged**
