### PR TITLE
Add test assets for WMF to PNG conversion test

### PR DESCRIPTION
**Pull request by safern**
These assets are needed for: https://github.com/dotnet/runtime/pull/35169

### CODE REVIEW

**Comment by tannergooding** [comment]
Do we have a NuGet package or somewhere we can add this to instead? Generally speaking, checking binary files into git isn't "best practice"...

If we are going to check them in, do we expect they will ever need to be removed or modified and if so, how frequently?

**Comment by ViktorHofer** [comment]
This repository's purpose is to generate nuget packages which are then consumed in dotnet/runtime.

**Comment by tannergooding** [comment]
> This repository's purpose is to generate nuget packages which are then consumed in dotnet/runtime.

I completely missed the `-assets` part of the name. My bad 😄

**Comment by safern** [comment]
> Where are those assets coming from? What's their license? :)

Those are just dummy images a internal costumer shared with me for the repro and said it was fine to put them in GH.

**Pull request merged**
