### PR TITLE
Update tests assets for .NET 9

### PR DESCRIPTION
**Pull request by joeloff**
Update tests assets to include a file that has a valid signature, but terminates in a non-Microsoft root certificate.

The asset is needed for tests that will be added to https://github.com/dotnet/sdk/pull/36787 to improve our sign verification for optional workloads in the SDK.

### CODE REVIEW

**Comment by ViktorHofer** [comment]
The asset is needed for tests that will be added to https://github.com/dotnet/sdk/pull/36787 to improve our sign verification for optional workloads in the SDK.

The purpose of this repository is to provide test assets for dotnet/runtime. I'm surprised that dotnet/sdk uses a package from here.

**Comment by joeloff** [comment]
I know. We asked for it back in 6.0 because we did not have a test asset repo for the SDK and dnceng was reluctant about adding one more repo for a single asset where we could keep binaries, so runtime agreed to it.

**Comment by ViktorHofer** [comment]
Interesting. We could rename this repo to make it available for broader use, i.e. `dotnet/test-assets`.

**Comment by akoeplinger** [comment]
There are not just tests in this repo, we also have the unicode and timezone data here. Maybe `repo-assets`?

**Review by akoeplinger — APPROVED** [review]

**Review by ViktorHofer — APPROVED** [review]
Maybe a rename isn't worth it. We would need to update the Version.Details.xml entries, ideally in all branches and consuming repos.

**Comment by joeloff** [comment]
> Maybe a rename isn't worth it. We would need to update the Version.Details.xml entries, ideally in all branches and consuming repos.

Thanks, maybe something to consider for the VMR?

**Pull request merged**
