### PR TITLE
Added Zip File containing files with characters invalid in Windows

### PR DESCRIPTION
**Pull request by Danyy427**
Relates to https://github.com/dotnet/runtime/issues/67201

### CODE REVIEW

**Comment by danmoseley** [comment]
Thanks. I improved the filename and added a clickable link to the original issue.

It's probably helpful to document what you have put in this zip:
```
dan@danmoseL:~/zip$ unzip -l InvalidWindowsFileNameChars.zip
Archive:  InvalidWindowsFileNameChars.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2022-03-27 13:44   Test/
       12  2022-03-27 13:44   Test/normalText.txt
        0  2022-03-27 13:44   Test"<>|^A^B^C^D^E^F^G^H^I^J^K^L^M^N^O^P^Q^R^S^T^U^V^W^X^Y^Z^[^\^]^^^_/
       14  2022-03-27 13:44   Test"<>|^A^B^C^D^E^F^G^H^I^J^K^L^M^N^O^P^Q^R^S^T^U^V^W^X^Y^Z^[^\^]^^^_/TestText1"<>|^A^B^C^D^E^F^G^H^I^J^K^L^M^N^O^P^Q^R^S^T^U^V^W^X^Y^Z^[^\^]^^^_.txt
        0  2022-03-27 13:44   TestEmpty/
       14  2022-03-27 13:44   TestText"<>|^A^B^C^D^E^F^G^H^I^J^K^L^M^N^O^P^Q^R^S^T^U^V^W^X^Y^Z^[^\^]^^^_.txt
```

where ^A == 0x01 through ^_ == 0x31. It looks like you are missing these three: '*', '?', ':'. Could you please add those too? (There is no perfect set of valid Windows filename chars, as it depends on position to some extent, and some names are reserved. But this does not need to be perfect. Anyone can fall back to extracting one file at a time using whatever filenames they like. But '*', '?', ':' seem reasonable to sanitize also.)

**Comment by Danyy427** [comment]
@danmoseley on it

**Comment by Danyy427** [comment]
@danmoseley I have added those three characters and committed the changes.

**Review by danmoseley — APPROVED** [review]

**Comment by danmoseley** [comment]
```
dan@danmoseL:~/zip$ unzip -l InvalidWindowsFileNameChars.zip
Archive:  InvalidWindowsFileNameChars.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2022-03-27 15:07   Test/
       12  2022-03-27 15:07   Test/normalText.txt
        0  2022-03-27 15:07   Test"<>|^A^B^C^D^E^F^G^H^I^J^K^L^M^N^O^P^Q^R^S^T^U^V^W^X^Y^Z^[^\^]^^^_*?:/
       14  2022-03-27 15:07   Test"<>|^A^B^C^D^E^F^G^H^I^J^K^L^M^N^O^P^Q^R^S^T^U^V^W^X^Y^Z^[^\^]^^^_*?:/TestText1"<>|^A^B^C^D^E^F^G^H^I^J^K^L^M^N^O^P^Q^R^S^T^U^V^W^X^Y^Z^[^\^]^^^_*?:.txt
        0  2022-03-27 15:07   TestEmpty/
       14  2022-03-27 15:07   TestText"<>|^A^B^C^D^E^F^G^H^I^J^K^L^M^N^O^P^Q^R^S^T^U^V^W^X^Y^Z^[^\^]^^^_*?:.txt
```

**Comment by danmoseley** [comment]
@Danyy427 I don't know how long it takes for this to insert itself into dotnet/runtime so that when you run the tests there, they see it.

However if you want to make progress meantime these instructions might help https://github.com/dotnet/runtime-assets/blob/main/README.md#optional-step-local-testing

**Pull request merged**
