### PR TITLE
Fix android failed build

### PR DESCRIPTION
**Pull request by aik-jahoda**
Add certificates needed for android build.
Follow up for dotnet/runtime#50230

cc @elinor-fung

### CODE REVIEW

**Review by wfurt — APPROVED** [review]
LGTM (assuming the files work on Android)

**Comment by elinor-fung** [comment]
It looks like these added certs are still using `RC2` for encryption, which is not supported on Android. Dumping info for one of the added certs under TestDataCertificates:

```
>  openssl pkcs12 -in ./TestDataCertificates/testclienteku.contoso.com.noRC2.pfx -info                      
...
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 2048
```

The `noRC2` versions of all the certs were created in order to avoid using RC2 (they use TripleDES instead). Dumping info for one of the certs under TestData:

```
> openssl pkcs12 -in ./TestData/testclienteku.contoso.com.noRC2.pfx -info 
...
PKCS7 Encrypted data: pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 2000
```

**Comment by aik-jahoda** [comment]
I added new commit, 
the info is:
> PKCS7 Encrypted data: pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 2048

**Comment by elinor-fung** [comment]
I just realized that the versions of `testselfsignedclienteku.contoso.com.pfx` and `testselfsignedservereku.contoso.com.pfx` under the `TestDataCertificates` folder are also using RC2 now. The existing versions in the `TestData` folder were already only using TripleDES instead of RC2, which is why we didn't have to add `noRC2` versions originally. Could you create `noRC2` versions of those too? Sorry, I know this is obnoxious.

**Comment by wfurt** [comment]
I'm wondering if we should make the noRC2 simply the default rather than creating separate files. 
I had similar problem as some super new versions of openssl (maybe in combination with distro) disable very old ciphers - like rc2 so we may see more failures going forward.

**Comment by elinor-fung** [comment]
cc @bartonjs for thoughts on noRC2/RC2 as the default for cert test data
I'd guess we'd hit the same problems / go with the same default for X509Certificates.TestData

**Comment by bartonjs** [comment]
> thoughts on noRC2/RC2 as the default for cert test data

We probably want to keep some in X509Certificates, since that's how Windows XP generated PFXes (and everyone else copied that behavior), but outside X509 it's not important... they can all be 3DES so long as they open everywhere.

**Comment by aik-jahoda** [comment]
I'll remove all *.noRC2.pfx and replace *.pfx with triple des.

**Comment by aik-jahoda** [comment]
@elinor-fung can you please verify the current version fulfil your requirements?

**Review by elinor-fung — APPROVED** [review]
Verified that we can load these on Android. Thanks, @aik-jahoda!

**Pull request merged**
