### PR TITLE
Add data set of regex patterns for testing

### PR DESCRIPTION
**Pull request by stephentoub**
These patterns were sourced by downloading permissively-licensed nuget packages and searching them for use of `new Regex(pattern, ...)`.  The data set will be used to help validate things like `Regex` compatibility.  Thanks to @marklio.

cc: @joperezr, @danmoseley

### CODE REVIEW

**Review by joperezr — APPROVED** [review]
Thanks for adding this. Is there a reason why we prefer .csv? Not really opposed to it, but patterns can have commas themselves, so if we ever wanted to add some extra column to the data we would need to keep the pattern to be the last one, which I guess it should be fine.

**Comment by stephentoub** [comment]
> Is there a reason why we prefer .csv?

What format would you recommend instead?

**Comment by joperezr** [comment]
If we think it is possible to add columns in the future or modify the structure, I was thinking we could use something more structured like Json for example. And then we could use JsonSerializer to escape the pattern if necessary, and then to easily get the object which we can later use in tests to loop through cases. Again, this might just be overkill if we think that we won't be changing the way this .csv looks today. A possible column I thought we may want to add potentially, would be sample input that should match each pattern for example.

**Comment by stephentoub** [comment]
Ok, I changed it to be json

**Comment by danmoseley** [comment]
That's funny a number of the popular ones are mine (all the `..\u003CLINE...` ones are from MSBuild and perhaps borrowed by others)

**Pull request merged**
