### PR TITLE
[wasm] Move zic from runtime

### PR DESCRIPTION
**Pull request by tqiu8**
Addresses [#45368](https://github.com/dotnet/runtime/issues/45368)

Corresponding [PR](https://github.com/dotnet/runtime/pull/45443) in runtime

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]
Nice, thank you!

**Comment by radical** [comment]
```xml
  <InputFolder>$(MSBuildProjectDirectory)/input</InputFolder>
     <OutputFolder>$(MSBuildProjectDirectory)/data</OutputFolder>
```

Instead of creating the folders in the source directory, use `$(OutputPath)`, so they will be created in `artifacts/`, and can get cleaned up correctly too.

```xml
     <InputFolder>$(OutputPath)/input</InputFolder>
     <OutputFolder>$(OutputPath)/data</OutputFolder>
```

**Comment by ViktorHofer** [comment]
LGTM, thanks. @radical's comment makes sense though to avoid a dirty repo.

**Comment by radical** [comment]
Actually, even better:
```xml
    <InputFolder>$(IntermediateOutputPath)/input</InputFolder>
    <OutputFolder>$(OutputPath)/data</OutputFolder>
```

The difference being that we use the `obj` folder (`$(IntermediateOutputPath)`) for `InputFolder`, which is meant for such intermediate things used to produce the final output.

**Comment by ViktorHofer** [comment]
I agree, the intermediate one would be better. I'll do some work here and will clean this up as well.

**Comment by akoeplinger** [comment]
We already remove the dir via `<RemoveDir Directories="$(InputFolder)" />` so the repo isn't dirty at the moment, but I agree :)

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/runtime-assets/pull/103

**Pull request merged**
