### PR TITLE
Add a CheckVersion target to check the TimeZoneDataVersion

### PR DESCRIPTION
**Pull request by lewing**
Thoughts on where to download the file and wether this should be run normally.

### CODE REVIEW

**Review by safern — COMMENTED** [review]
Do we want to enable this on CI so that we catch it whenever it is outdated?

**Comment by lewing** [comment]
I'm not sure, a warning would be useful but I don't think it is worth breaking the build and should we check in dotnet/runtime on the consuming side as well?

**Review by akoeplinger — APPROVED** [review]
LGTM. I think adding the warning to CI either here or dotnet/runtime would be good.

**Comment by safern** [comment]
The problem with adding it to dotnet/runtime is that we have warnaserror enabled, and that warning would be treated as an error and break all PRs until we go and update the data version.

**Review by tqiu8 — APPROVED** [review]

**Pull request merged**
