### PR TITLE
Add podman tar for relative symlinks test

### PR DESCRIPTION
**Pull request by am11**
Test asset for https://github.com/dotnet/runtime/issues/77303.

### CODE REVIEW

**Comment by akoeplinger** [comment]
Where is that file coming from?

**Comment by am11** [comment]
@akoeplinger, linked issue has details.

**Comment by akoeplinger** [comment]
Ok but I don't think it should be going into the go test assets directory since it's not from their test suite and that might be confusing.

**Comment by am11** [comment]
We added docker in the same spirit last week https://github.com/dotnet/runtime-assets/pull/279. Since they both use golang, I added it there. I'm open for ideas if you prefer another directory for these. 🙂

**Comment by akoeplinger** [comment]
I'd just create a separate folder next to golang_tar. The files in that folder are coming from https://github.com/golang/go/tree/master/src/archive/tar/testdata so I think it'd be good to have separation (also license wise)

Btw. looks like there was a new test file added in https://github.com/golang/go/commit/0bf7ee9977c0218562c50a0b0f0d9cbdf33f65e6 that we might want to port too.

**Comment by am11** [comment]
Moved to `misc/` dir, and ported the new test from golang repo.

**Review by akoeplinger — APPROVED** [review]

**Comment by am11** [comment]
It's 1MB, I'll compress it with gz (they had it as bz2, which we don't support OOTB).

**Comment by akoeplinger** [comment]
I don't think 1MB is an issue fwiw

**Comment by am11** [comment]
> I don't think 1MB is an issue fwiw

We don't add huge files in this repo. Majority of files in golang dir are < 20 K.

**Comment by tmds** [comment]
The `tar` file from `docker` added in https://github.com/dotnet/runtime-assets/pull/279 is an invalid file.
`docker` (and `go` <= 1.8) include file type bits which should not be there.
Because it's invalid, that file cannot be generated using the .NET api.

The `tar` file that gets added here is a valid one.
It is meant to test [this branch](https://github.com/dotnet/runtime/blob/ddebaf5d7c547b688466897522eb7b01da54f2d9/src/libraries/System.Formats.Tar/src/System/Formats/Tar/TarEntry.cs#L352-L356) in the .NET implementation. There is nothing `go`/`podman` specific about this.
Rather than adding a file, this archive could be generated by the test using the .NET api.
Personally, I prefer tests generating the archive if possible, as that makes more visible what is special about the archive under test.

**Comment by am11** [comment]
@akoeplinger, looks like auto-merge got cancelled. can you manually merge?

**Comment by akoeplinger** [comment]
I didn't yet because @tmds raised a question about generating the file instead, do we want to do that? or are we fine with the checked in file?

**Comment by am11** [comment]
I think we can do both. This one is for consistency that the podman and docker archives are exercised (these are small files). It will help projects like https://github.com/WeihanLi/nocker to use System.Formats.Tar with confidence.

**Comment by akoeplinger** [comment]
Ok sounds good.

**Pull request merged**
