### PR TITLE
Add test certs that don't use RC2 to System.Net.TestData and System.Security.Cryptography.X509Certificates.TestData

### PR DESCRIPTION
**Pull request by elinor-fung**
Created by importing the original certs (that use RC2) on Windows and re-exporting them to generate versions without RC2.

cc @jkoritzinsky @steveisok @AaronRobinsonMSFT @bartonjs @wfurt

### CODE REVIEW

**Comment by bartonjs** [comment]
The diff view says all the new files are empty, instead of added as binary files.

**Comment by elinor-fung** [comment]
Do I need to do something special to add them differently?
If I go to 'view file' in the diff, it does show the size and I can download the (non-empty) binary file.

**Review by bartonjs — APPROVED** [review]

**Comment by bartonjs** [comment]
Must be a UI bug, then.

I don't know how new packages get published from here... so I'm not sure how we'll consume it from the tests.

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by elinor-fung** [comment]
My understanding is that once this goes in, a CI build will publish the new packages. The runtime repo subscribes to this as a dependency, so a PR should automatically be opened to update to the new package versions. And once that goes in, we can consume the new files from the tests.

**Comment by jkoritzinsky** [comment]
Elinor's description is correct. We should get a package with the updated data files within about a day at max automatically consumed in dotnet/runtime.

**Review by jkoritzinsky — APPROVED** [review]

**Comment by bartonjs** [comment]
Oh, nice.  The last time I updated this package it involved a lot of tracking people down for manual builds and uploads :smile:.

And all of this was fields.  And I had to walk to school barefoot.  In the snow.  Uphill.  Both ways.

**Comment by danmoseley** [comment]
cc @aik-jahoda

**Pull request merged**
