### PR TITLE
download backward compat file from iana

### PR DESCRIPTION
**Pull request by tqiu8**
Add backward compatibility file from iana which includes different version names of tz ids.

### CODE REVIEW

**Comment by ViktorHofer** [comment]
/azp run runtime-assets.

@tqiu8 I assume this isn't needed for 5.0, right?

**Comment by tqiu8** [comment]
@ViktorHofer no it's not

**Comment by lewing** [comment]
This is a fix for https://github.com/dotnet/runtime/issues/43518

**Comment by lewing** [comment]
Actually we should get this in 5.0 servicing even if we miss GA

**Comment by ViktorHofer** [comment]
> Actually we should get this in 5.0 servicing even if we miss GA

For that we need tactics approval.

**Comment by lewing** [comment]
> > Actually we should get this in 5.0 servicing even if we miss GA
> 
> For that we need tactics approval.

I'm aware.  I'll send the email once we've verified the fix.

**Review by safern — APPROVED** [review]

**Comment by lewing** [comment]
The full fix will need some more work but it starts with including this in the assets.

**Pull request merged**
